from django.urls import path
from . import views

urlpatterns = [
    path("admission/", views.admission_form, name="admission_form"),
    path("principal/", views.principal_dashboard, name="principal_dashboard"),
    path("approve/<int:pk>/", views.approve_application, name="approve_application"),
    path("reject/<int:pk>/", views.reject_application, name="reject_application"),
    path("student/dashboard/", views.student_dashboard, name="student_dashboard"),
    path("parent/dashboard/", views.parent_dashboard, name="parent_dashboard"),
    path("teacher/dashboard/", views.teacher_dashboard, name="teacher_dashboard"),
    path("teacher/attendance/", views.teacher_mark_attendance, name="teacher_mark_attendance"),
    path("student/report-card/", views.download_report_card, name="download_report_card"),
    path("student/submit-homework/", views.submit_homework, name="submit_homework"),
    path("teacher/question-paper/", views.upload_question_paper, name="upload_question_paper"),
    path("teacher/submissions/", views.view_submissions, name="view_submissions"),
    path("teacher/marks/", views.teacher_enter_marks, name="teacher_enter_marks"),
    path("teacher/homework/", views.upload_homework, name="upload_homework"),
    path("teacher/homework/edit/<int:hw_id>/", views.edit_homework, name="edit_homework"),
    path("teacher/homework/delete/<int:hw_id>/", views.delete_homework, name="delete_homework"),
    path("teacher/attendance/edit/<int:record_id>/",views.edit_attendance,name="edit_attendance"),
    path("teacher/question-paper/edit/<int:paper_id>/",views.edit_question_paper,name="edit_question_paper"),
    path("teacher/question-paper/delete/<int:paper_id>/",views.delete_question_paper,name="delete_question_paper"),
    path("teacher/marks/edit/<int:mark_id>/", views.edit_mark, name="edit_mark"),
    path("teacher/marks/delete/<int:mark_id>/", views.delete_mark, name="delete_mark"),
    path("student/attendance/", views.student_attendance, name="student_attendance"),
    path("student/marks/", views.student_marks, name="student_marks"),
    path("student/homework/", views.student_homework, name="student_homework"),
    path("student/question-papers/", views.student_question_papers, name="student_question_papers"),
    path("parent/download-report/", views.download_report, name="download_report"),
    path("parent/marks/", views.parent_marks, name="parent_marks"),
    path("parent/attendance/", views.parent_attendance, name="parent_attendance"),
    path("principal/classes/", views.principal_class_list, name="principal_class_list"),
    path("principal/classes/edit/<int:class_id>/", views.principal_edit_class, name="principal_edit_class"),
    path("principal/classes/delete/<int:class_id>/", views.principal_delete_class, name="principal_delete_class"),
    path("principal/classes/delete/<int:class_id>/",views.principal_delete_class,name="principal_delete_class"),
    path("principal/reports/",views.principal_reports,name="principal_reports"),
    path("student/homework/",views.student_homework,name="student_homework"),
    path("student/homework/submit/<int:homework_id>/",views.submit_homework,name="submit_homework"),
    path("student/homework/delete/<int:homework_id>/",views.delete_submission,name="delete_submission"),
]
