# Generated by Django 6.0 on 2026-02-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='class_obj',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='date',
        ),
        migrations.AddField(
            model_name='exam',
            name='max_marks',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
