# Generated by Django 6.0 on 2026-02-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_remove_exam_class_obj_remove_exam_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='marks_obtained',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='teacher',
        ),
        migrations.AddField(
            model_name='mark',
            name='marks',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
