# Generated by Django 6.0 on 2026-02-28 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_section_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.section'),
        ),
    ]
